---
- hosts: local
  vars:
    brew_sh:
      - bat
      - exa
      - git
      - python3
    brew_gui:
      - 1password
      - brave-browser
      - calibre
      - discord
      - firefox
      - goland
      - iterm2
      - postman
      - rectangle
      - slack
      - spotify
      - typora
      - vlc
      - visual-studio-code
  tasks:
    - name: Install utils with brew
      homebrew: name={{ item }} state=present
      with_items: '{{ brew_sh }}'

    - name: Install GUI apps with brew
      homebrew_cask: name={{ item }} state=present
      with_items: '{{ brew_gui }}'

    - name: Configure mac system settings
      script: ./scripts/configure-mac.sh

    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    - name: Install p10k
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
        clone: yes

    - name: Install zsh syntax highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        clone: yes

    - name: Install zsh auto-suggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        clone: yes

    - name: Copy config files
      copy:
        src: ./config/dotfiles/
        dest: ~/

    - name: Copy font files
      copy:
        src: ./config/fonts/
        dest: ~/Library/Fonts/
